<script>
  let { schema, options, bbdb_action } = $props();
  import { emit_bbdb_event } from "$lib/bbdb_actions.js";
  import { onMount } from "svelte";
  import JsonEditor from "$lib/utils/JSONEditor.svelte";
  let loaded = $state(false);
  let new_data = $state({})
  let new_data_validity = $state(false)
  let new_adding = $state(false) // true when add button is clicked 
  let new_status = $state("")
  onMount(() => {
    loaded = true

    console.log(schema)
  });
  const on_add_click = async ()=>{
    try {
      new_adding = true
      new_status = "Creating new document..."
      let resp = await bbdb_action(emit_bbdb_event("new_document",{schema:schema.name,data:new_data}))
      new_adding = false
      if (resp.added){
        // added 
        new_data = {}
        //new_adding = false
        new_status= "Added!"
      }else{
        //new_adding = false
        new_status = resp.error
      }
    } catch (error) {
      new_adding = false
      new_status = error.message
    }
  }
</script>

{#if loaded}
<h4>New {schema.title}</h4>
  <p>
    
    {#if schema.system_generated}
      <span  title="This schema was generated by the BeanBagDB system"  class= "badge text-bg-secondary">System</span> <span class="badge text-bg-secondary">v{schema.version}</span>
    {/if}
    {schema.description}
  </p>
  {#if schema.name=="schema"}
    schema
  {:else}
    <JsonEditor bind:data={new_data} schema={schema.schema} bind:data_valid={new_data_validity}/>
  {/if}

{/if}

<br>
{#if new_data_validity}

  {#if new_status}
    <div class="alert alert-info">
      {new_status}
    </div> 
  {/if} 
  {#if !new_adding }
  <button class="btn btn-primary" onclick={on_add_click} >+ Add</button>
  {/if}

{/if}